namespace System.Web.Services.Description;

/// <summary>Specifies the type of warnings produced by <see cref="M:System.Web.Services.Description.ServiceDescriptionImporter.Import(System.CodeDom.CodeNamespace,System.CodeDom.CodeCompileUnit)" />.</summary>
[Flags]
public enum ServiceDescriptionImportWarnings
{
	/// <summary>Specifies that no proxy class was generated by the <see cref="M:System.Web.Services.Description.ServiceDescriptionImporter.Import(System.CodeDom.CodeNamespace,System.CodeDom.CodeCompileUnit)" /> method.</summary>
	NoCodeGenerated = 1,
	/// <summary>Specifies that at least one optional <see cref="T:System.Web.Services.Description.ServiceDescriptionFormatExtension" /> for the <see cref="T:System.Web.Services.Description.ServiceDescription" /> to be imported has been ignored.</summary>
	OptionalExtensionsIgnored = 2,
	/// <summary>Specifies that at least one required <see cref="T:System.Web.Services.Description.ServiceDescriptionFormatExtension" /> for the <see cref="T:System.Web.Services.Description.ServiceDescription" /> to be imported has been ignored.</summary>
	RequiredExtensionsIgnored = 4,
	/// <summary>Specifies that at least one <see cref="T:System.Web.Services.Description.Operation" /> for the <see cref="T:System.Web.Services.Description.ServiceDescription" /> to be imported is of an unsupported type and has been ignored.</summary>
	UnsupportedOperationsIgnored = 8,
	/// <summary>Specifies that at least one <see cref="T:System.Web.Services.Description.Binding" /> for the <see cref="T:System.Web.Services.Description.ServiceDescription" /> to be imported is of an unsupported type and has been ignored.</summary>
	UnsupportedBindingsIgnored = 0x10,
	/// <summary>Specifies that the proxy class generated by the <see cref="M:System.Web.Services.Description.ServiceDescriptionImporter.Import(System.CodeDom.CodeNamespace,System.CodeDom.CodeCompileUnit)" /> method includes no methods.</summary>
	NoMethodsGenerated = 0x20,
	/// <summary>Specifies that the <see cref="T:System.Web.Services.Description.ServiceDescription" /> schema is invalid.</summary>
	SchemaValidation = 0x40,
	/// <summary>Specifies that the <see cref="T:System.Web.Services.Description.ServiceDescription" /> to be imported does not conform to the WS-I Basic Profile.</summary>
	WsiConformance = 0x80
}
