namespace System.Web.Util;

internal enum AppVerifierErrorCode
{
	Ok,
	HttpApplicationInstanceWasNull,
	BeginHandlerDelegateWasNull,
	AsyncCallbackInvokedMultipleTimes,
	AsyncCallbackInvokedWithNullParameter,
	AsyncCallbackGivenAsyncResultWhichWasNotCompleted,
	AsyncCallbackInvokedSynchronouslyButAsyncResultWasNotMarkedCompletedSynchronously,
	AsyncCallbackInvokedAsynchronouslyButAsyncResultWasMarkedCompletedSynchronously,
	AsyncCallbackInvokedWithUnexpectedAsyncResultInstance,
	AsyncCallbackInvokedAsynchronouslyThenBeginHandlerThrew,
	BeginHandlerThrewThenAsyncCallbackInvokedAsynchronously,
	AsyncCallbackInvokedSynchronouslyThenBeginHandlerThrew,
	AsyncCallbackInvokedWithUnexpectedAsyncResultAsyncState,
	AsyncCallbackCalledAfterHttpApplicationReassigned,
	BeginHandlerReturnedNull,
	BeginHandlerReturnedAsyncResultMarkedCompletedSynchronouslyButWhichWasNotCompleted,
	BeginHandlerReturnedAsyncResultMarkedCompletedSynchronouslyButAsyncCallbackNeverCalled,
	BeginHandlerReturnedUnexpectedAsyncResultInstance,
	BeginHandlerReturnedUnexpectedAsyncResultAsyncState,
	SyncContextSendOrPostCalledAfterRequestCompleted,
	SyncContextSendOrPostCalledBetweenNotifications,
	SyncContextPostCalledInNestedNotification,
	RequestNotificationCompletedSynchronouslyWithNotificationContextPending,
	NotificationContextHasChangedAfterSynchronouslyProcessingNotification,
	PendingProcessRequestNotificationStatusAfterCompletingNestedNotification
}
