using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace System.Web.Properties;

[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
[DebuggerNonUserCode]
[CompilerGenerated]
internal class Resources
{
	private static ResourceManager resourceMan;

	private static CultureInfo resourceCulture;

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	internal static ResourceManager ResourceManager
	{
		get
		{
			if (resourceMan == null)
			{
				resourceMan = new ResourceManager("TranslationResources", typeof(Resources).Assembly);
			}
			return resourceMan;
		}
	}

	[EditorBrowsable(EditorBrowsableState.Advanced)]
	internal static CultureInfo Culture
	{
		get
		{
			return resourceCulture;
		}
		set
		{
			resourceCulture = value;
		}
	}

	internal static string ErrArgumentNull => ResourceManager.GetString("ErrArgumentNull", resourceCulture);

	internal static string ErrArgumentNullOrEmpty => ResourceManager.GetString("ErrArgumentNullOrEmpty", resourceCulture);

	internal static string ErrAutoGeneratedKeyNotSupported => ResourceManager.GetString("ErrAutoGeneratedKeyNotSupported", resourceCulture);

	internal static string ErrCantDecodeHashedPw => ResourceManager.GetString("ErrCantDecodeHashedPw", resourceCulture);

	internal static string ErrCantDeletePopulatedRole => ResourceManager.GetString("ErrCantDeletePopulatedRole", resourceCulture);

	internal static string ErrCantLogoutUser => ResourceManager.GetString("ErrCantLogoutUser", resourceCulture);

	internal static string ErrCantRetrieveHashedPw => ResourceManager.GetString("ErrCantRetrieveHashedPw", resourceCulture);

	internal static string ErrCantUpdateFailtureCount => ResourceManager.GetString("ErrCantUpdateFailtureCount", resourceCulture);

	internal static string ErrCantUpdateFailtureCountAndWindowStart => ResourceManager.GetString("ErrCantUpdateFailtureCountAndWindowStart", resourceCulture);

	internal static string ErrConnectionStringNullOrEmpty => ResourceManager.GetString("ErrConnectionStringNullOrEmpty", resourceCulture);

	internal static string ErrIncorrectPasswordAnswer => ResourceManager.GetString("ErrIncorrectPasswordAnswer", resourceCulture);

	internal static string ErrOperationAborted => ResourceManager.GetString("ErrOperationAborted", resourceCulture);

	internal static string ErrPasswordAnswerRequired => ResourceManager.GetString("ErrPasswordAnswerRequired", resourceCulture);

	internal static string ErrPasswordChangeCanceled => ResourceManager.GetString("ErrPasswordChangeCanceled", resourceCulture);

	internal static string ErrPasswordResetAborted => ResourceManager.GetString("ErrPasswordResetAborted", resourceCulture);

	internal static string ErrPasswordResetCanceled => ResourceManager.GetString("ErrPasswordResetCanceled", resourceCulture);

	internal static string ErrPasswordResetNotEnabled => ResourceManager.GetString("ErrPasswordResetNotEnabled", resourceCulture);

	internal static string ErrPasswordRetrievalNotEnabled => ResourceManager.GetString("ErrPasswordRetrievalNotEnabled", resourceCulture);

	internal static string ErrProfileAlreadyExist => ResourceManager.GetString("ErrProfileAlreadyExist", resourceCulture);

	internal static string ErrPwFormatNotSupported => ResourceManager.GetString("ErrPwFormatNotSupported", resourceCulture);

	internal static string ErrRoleAlreadyExist => ResourceManager.GetString("ErrRoleAlreadyExist", resourceCulture);

	internal static string ErrRoleNotExist => ResourceManager.GetString("ErrRoleNotExist", resourceCulture);

	internal static string ErrRollbackFailed => ResourceManager.GetString("ErrRollbackFailed", resourceCulture);

	internal static string ErrUserAlreadyInRole => ResourceManager.GetString("ErrUserAlreadyInRole", resourceCulture);

	internal static string ErrUserIsLoggedOut => ResourceManager.GetString("ErrUserIsLoggedOut", resourceCulture);

	internal static string ErrUserIsNotInRole => ResourceManager.GetString("ErrUserIsNotInRole", resourceCulture);

	internal static string ErrUserNotFound => ResourceManager.GetString("ErrUserNotFound", resourceCulture);

	internal static string LogRollbackAttempt => ResourceManager.GetString("LogRollbackAttempt", resourceCulture);

	internal static string MembershipProviderDefaultDescription => ResourceManager.GetString("MembershipProviderDefaultDescription", resourceCulture);

	internal static string MembershipProviderDefaultName => ResourceManager.GetString("MembershipProviderDefaultName", resourceCulture);

	internal static string ProfileProviderDefaultDescription => ResourceManager.GetString("ProfileProviderDefaultDescription", resourceCulture);

	internal static string ProfileProviderDefaultName => ResourceManager.GetString("ProfileProviderDefaultName", resourceCulture);

	internal static string RoleProviderDefaultDescription => ResourceManager.GetString("RoleProviderDefaultDescription", resourceCulture);

	internal static string RoleProviderDefaultName => ResourceManager.GetString("RoleProviderDefaultName", resourceCulture);

	internal static string SessionStoreProviderDefaultDescription => ResourceManager.GetString("SessionStoreProviderDefaultDescription", resourceCulture);

	internal static string SessionStoreProviderDefaultName => ResourceManager.GetString("SessionStoreProviderDefaultName", resourceCulture);

	internal Resources()
	{
	}
}
