namespace Novell.Directory.Ldap.Events.Edir;

public enum EdirEventDataType
{
	EDIR_TAG_ENTRY_EVENT_DATA = 1,
	EDIR_TAG_VALUE_EVENT_DATA,
	EDIR_TAG_GENERAL_EVENT_DATA,
	EDIR_TAG_SKULK_DATA,
	EDIR_TAG_BINDERY_EVENT_DATA,
	EDIR_TAG_DSESEV_INFO,
	EDIR_TAG_MODULE_STATE_DATA,
	EDIR_TAG_NETWORK_ADDRESS,
	EDIR_TAG_CONNECTION_STATE,
	EDIR_TAG_CHANGE_SERVER_ADDRESS,
	EDIR_TAG_CHANGE_CONFIG_PARAM,
	EDIR_TAG_NO_DATA,
	EDIR_TAG_STATUS_LOG,
	EDIR_TAG_DEBUG_EVENT_DATA
}
