namespace Novell.Directory.Ldap.Events.Edir;

public enum GeneralEventField
{
	EVT_TAG_GEN_DSTIME = 1,
	EVT_TAG_GEN_MILLISEC,
	EVT_TAG_GEN_VERB,
	EVT_TAG_GEN_CURRPROC,
	EVT_TAG_GEN_PERP,
	EVT_TAG_GEN_INTEGERS,
	EVT_TAG_GEN_STRINGS
}
