using System.Security.Permissions;

namespace System.Web.UI.WebControls;

/// <summary>Represents the properties of an <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object. This class cannot be inherited.</summary>
[AspNetHostingPermission(SecurityAction.LinkDemand, Level = AspNetHostingPermissionLevel.Minimal)]
[AspNetHostingPermission(SecurityAction.InheritanceDemand, Level = AspNetHostingPermissionLevel.Minimal)]
public sealed class AutoGeneratedFieldProperties : IStateManager
{
	private StateBag ViewState = new StateBag();

	/// <summary>Gets or sets the name of the field bound to the <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object.</summary>
	/// <returns>The name of the field bound to the <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" />. The default is an empty string (""), which indicates that this property is not set.</returns>
	public string DataField
	{
		get
		{
			return ViewState.GetString("DataField", string.Empty);
		}
		set
		{
			ViewState["DataField"] = value;
		}
	}

	/// <summary>Gets or sets a value indicating whether the values displayed in an <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object can be modified in edit mode.</summary>
	/// <returns>
	///     <see langword="true" /> to indicate that the values are read-only; otherwise, <see langword="false" />. The default is <see langword="false" />.</returns>
	public bool IsReadOnly
	{
		get
		{
			return ViewState.GetBool("IsReadOnly", def: false);
		}
		set
		{
			ViewState["IsReadOnly"] = value;
		}
	}

	/// <summary>Gets or sets the name of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object.</summary>
	/// <returns>The name of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedField" /> object. The default is an empty string (""), which indicates that this property is not set.</returns>
	public string Name
	{
		get
		{
			return ViewState.GetString("Name", string.Empty);
		}
		set
		{
			ViewState["Name"] = value;
		}
	}

	/// <summary>Gets or sets the data type of the value displayed in an <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object.</summary>
	/// <returns>A <see cref="T:System.Type" /> that represents the data type of the value displayed in an <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object. The default is <see langword="null" />, which indicates that this property is not set.</returns>
	public Type Type
	{
		get
		{
			object obj = ViewState["Type"];
			if (obj != null)
			{
				return (Type)obj;
			}
			return null;
		}
		set
		{
			ViewState["Type"] = value;
		}
	}

	/// <summary>Gets a value indicating whether the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object is tracking its view-state changes.</summary>
	/// <returns>
	///     <see langword="true" /> to indicate that the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object is tracking its view-state changes; otherwise, <see langword="false" />.</returns>
	bool IStateManager.IsTrackingViewState => ViewState.IsTrackingViewState;

	/// <summary>Loads the previously saved view state of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object.</summary>
	/// <param name="state">An <see cref="T:System.Object" /> that represents the state of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" />.</param>
	void IStateManager.LoadViewState(object state)
	{
		ViewState.LoadViewState(state);
	}

	/// <summary>Saves the current view state of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object.</summary>
	/// <returns>An <see cref="T:System.Object" /> that contains the saved state of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object.</returns>
	object IStateManager.SaveViewState()
	{
		return ViewState.SaveViewState();
	}

	/// <summary>Marks the starting point at which to begin tracking and saving view-state changes to the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> object.</summary>
	void IStateManager.TrackViewState()
	{
		ViewState.TrackViewState();
	}

	/// <summary>Initializes a new instance of the <see cref="T:System.Web.UI.WebControls.AutoGeneratedFieldProperties" /> class.</summary>
	public AutoGeneratedFieldProperties()
	{
	}
}
